alias vi="vim"
alias i3-config="vim $HOME/.config/i3/config"
alias poly-config="vim $HOME/.config/polybar/config"
alias terminal-colors="for code ({000..255}) print -P -- \"\$code: %F{\$code}This is how your text would look like%f\""
alias custom-theme="vim $HOME/.oh-my-zsh/custom/themes/custom.zsh-theme"
alias spotify-info="$HOME/spotify-track/spotify-track i"
alias grep="grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn -i"
alias correct-kb="setxkbmap -layout us -variant altgr-intl -option nodeadkeys"
alias hd="hexdump -C"
alias gdb="gdb -q"
alias jn="jupyter notebook"
alias simus="$HOME/packages/simus_lin64"
alias memusage="sudo ncdu -rx /"
