#!/bin/bash

# Specifying the icon(s) in the script
# This allows us to change its appearance conditionally
icon=" "

player_status=$(playerctl -p spotify status 2> /dev/null)
metadata="$(playerctl -p spotify metadata artist 2> /dev/null) - $(playerctl metadata title 2> /dev/null)"

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    #echo "%{F#D08770}$icon $metadata"       # Orange when playing
	echo "%{F#4bffdc}$icon  %{F#65737E}$metadata"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#65737E}$icon $metadata"       # Greyed out info when paused
# else
    # echo "%{F#65737E}$icon"                 # Greyed out icon when stopped
fi
